import { FeatureItem } from '../models/user.model';

export const FEATURES: FeatureItem[] = [
  {
    id: 'admins',
    titulo: 'Gerenciar Administradores',
    descricao: 'Cadastrar, listar, excluir e alterar credenciais de outros admins.',
    icone: 'admin_panel_settings',
    roles: ['ADMIN'],
    superAdminOnly: true,
  },
  {
    id: 'usuarios',
    titulo: 'Gerenciar Alunos',
    descricao: 'Listar, cadastrar, editar e excluir alunos.',
    icone: 'groups',
    roles: ['ADMIN'],
  },
  {
    id: 'professores',
    titulo: 'Gerenciar Professores',
    descricao: 'Listar, cadastrar, editar e excluir professores.',
    icone: 'school',
    roles: ['ADMIN'],
  },
  {
    id: 'disciplinas',
    titulo: 'Gerenciar Disciplinas',
    descricao: 'Listar e cadastrar disciplinas vinculadas a professores.',
    icone: 'menu_book',
    roles: ['ADMIN'],
  },
  {
    id: 'todos-trabalhos',
    titulo: 'Todos os Trabalhos',
    descricao: 'Visualizar e acompanhar todos os trabalhos acadêmicos.',
    icone: 'assignment',
    roles: ['ADMIN'],
  },
  {
    id: 'avaliar-entregas',
    titulo: 'Avaliar Entregas',
    descricao: 'Corrigir e atribuir notas às entregas dos alunos.',
    icone: 'grading',
    roles: ['PROFESSOR'],
  },
  {
    id: 'alunos-orientandos',
    titulo: 'Alunos Orientandos',
    descricao: 'Acompanhar alunos sob sua orientação.',
    icone: 'supervisor_account',
    roles: ['PROFESSOR'],
  },
  {
    id: 'temas-pesquisa',
    titulo: 'Temas de Pesquisa',
    descricao: 'Definir e gerenciar temas disponíveis para TCC.',
    icone: 'lightbulb',
    roles: ['PROFESSOR'],
  },
  {
    id: 'meus-trabalhos',
    titulo: 'Meus Trabalhos',
    descricao: 'Consultar trabalhos atribuídos e prazos.',
    icone: 'assignment_turned_in',
    roles: ['ALUNO'],
  },
  {
    id: 'entregar-trabalho',
    titulo: 'Entregar Trabalho',
    descricao: 'Enviar arquivos e registrar entregas.',
    icone: 'upload_file',
    roles: ['ALUNO'],
  },
  {
    id: 'minhas-notas',
    titulo: 'Minhas Notas',
    descricao: 'Visualizar notas e feedback dos professores.',
    icone: 'star_rate',
    roles: ['ALUNO'],
  },
  {
    id: 'orientador',
    titulo: 'Meu Orientador',
    descricao: 'Ver dados do professor orientador.',
    icone: 'person_search',
    roles: ['ALUNO'],
  },
];
